apiVersion: v1
kind: Service
metadata:
  labels:
    app: pacman-kikd
  name: pacman-kikd
  namespace: pacman
  spec:
    ports:
      - name: http
        port: 8080
        targetPort: 8080
    selector:
      app: pacman-kikd
