resources:
- ../base
- namespace.yaml

patches:
- path: deployment.yaml
- path: services.yaml
- path: route.yaml

namespace: production
namePrefix: prd-
nameSuffix: -v0-9
commonLabels:
  app: prd-web-wdpress

